"""fix pokemons

Revision ID: 3561fc0b6d8c
Revises: dec7d96d5844
Create Date: 2021-06-21 19:49:02.376961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3561fc0b6d8c'
down_revision = 'dec7d96d5844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'pokemon_id')
    )
    op.create_index(op.f('ix_user_pokemon_id'), 'user_pokemon', ['id'], unique=False)
    op.drop_index('ix_userpokemon_id', table_name='userpokemon')
    op.drop_table('userpokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpokemon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='userpokemon_owner_id_fkey'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name='userpokemon_pokemon_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userpokemon_pkey')
    )
    op.create_index('ix_userpokemon_id', 'userpokemon', ['id'], unique=False)
    op.drop_index(op.f('ix_user_pokemon_id'), table_name='user_pokemon')
    op.drop_table('user_pokemon')
    # ### end Alembic commands ###
