"""make user-pokemon ids string

Revision ID: ea733a57ee72
Revises: 3561fc0b6d8c
Create Date: 2021-06-26 14:24:36.176415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea733a57ee72'
down_revision = '3561fc0b6d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pokemon', sa.Column('user', sa.Integer(), nullable=True))
    op.add_column('user_pokemon', sa.Column('pokemon', sa.Integer(), nullable=True))
    op.alter_column('user_pokemon', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_user_pokemon_pokemon'), 'user_pokemon', ['pokemon'], unique=False)
    op.create_index(op.f('ix_user_pokemon_user'), 'user_pokemon', ['user'], unique=False)
    op.drop_constraint('user_pokemon_pokemon_id_fkey', 'user_pokemon', type_='foreignkey')
    op.drop_constraint('user_pokemon_user_id_fkey', 'user_pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'user_pokemon', 'pokemon', ['pokemon'], ['id'])
    op.create_foreign_key(None, 'user_pokemon', 'user', ['user'], ['id'])
    op.drop_column('user_pokemon', 'user_id')
    op.drop_column('user_pokemon', 'pokemon_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pokemon', sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_pokemon', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_pokemon', type_='foreignkey')
    op.drop_constraint(None, 'user_pokemon', type_='foreignkey')
    op.create_foreign_key('user_pokemon_user_id_fkey', 'user_pokemon', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_pokemon_pokemon_id_fkey', 'user_pokemon', 'pokemon', ['pokemon_id'], ['id'])
    op.drop_index(op.f('ix_user_pokemon_user'), table_name='user_pokemon')
    op.drop_index(op.f('ix_user_pokemon_pokemon'), table_name='user_pokemon')
    op.alter_column('user_pokemon', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user_pokemon', 'pokemon')
    op.drop_column('user_pokemon', 'user')
    # ### end Alembic commands ###
